language: node_js
node_js: "8"
branches:
  only:
  - master
env:
  - username=travis
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;' -u root
services:
  - mysql